<?php

namespace App\Support\GeoFlow;

final class GscCountryName
{
    /**
     * @var array<string, string>
     */
    private const NAMES = [
        'AFG' => '阿富汗',
        'AGO' => '安哥拉',
        'AIA' => '安圭拉',
        'ALB' => '阿尔巴尼亚',
        'AND' => '安道尔',
        'ARE' => '阿拉伯联合酋长国',
        'ARG' => '阿根廷',
        'ARM' => '亚美尼亚',
        'ATG' => '安提瓜和巴布达',
        'AUS' => '澳大利亚',
        'AUT' => '奥地利',
        'AZE' => '阿塞拜疆',
        'BEL' => '比利时',
        'BES' => '荷兰加勒比区',
        'BFA' => '布基纳法索',
        'BGD' => '孟加拉国',
        'BGR' => '保加利亚',
        'BHR' => '巴林',
        'BHS' => '巴哈马',
        'BIH' => '波斯尼亚和黑塞哥维那',
        'BLM' => '圣巴泰勒米',
        'BLR' => '白俄罗斯',
        'BLZ' => '伯利兹',
        'BMU' => '百慕大',
        'BOL' => '玻利维亚',
        'BRA' => '巴西',
        'BRB' => '巴巴多斯',
        'BRN' => '文莱',
        'BTN' => '不丹',
        'BWA' => '博茨瓦纳',
        'CAN' => '加拿大',
        'CHE' => '瑞士',
        'CHL' => '智利',
        'CHN' => '中国',
        'CIV' => '科特迪瓦',
        'CMR' => '喀麦隆',
        'COD' => '刚果（金）',
        'COG' => '刚果（布）',
        'COK' => '库克群岛',
        'COL' => '哥伦比亚',
        'CPV' => '佛得角',
        'CRI' => '哥斯达黎加',
        'CUB' => '古巴',
        'CYM' => '开曼群岛',
        'CYP' => '塞浦路斯',
        'CZE' => '捷克',
        'DEU' => '德国',
        'DNK' => '丹麦',
        'DOM' => '多米尼加共和国',
        'DZA' => '阿尔及利亚',
        'ECU' => '厄瓜多尔',
        'EGY' => '埃及',
        'ESH' => '西撒哈拉',
        'ESP' => '西班牙',
        'EST' => '爱沙尼亚',
        'ETH' => '埃塞俄比亚',
        'FIN' => '芬兰',
        'FJI' => '斐济',
        'FRA' => '法国',
        'FRO' => '法罗群岛',
        'GAB' => '加蓬',
        'GBR' => '英国',
        'GEO' => '格鲁吉亚',
        'GGY' => '根西岛',
        'GHA' => '加纳',
        'GIB' => '直布罗陀',
        'GIN' => '几内亚',
        'GNB' => '几内亚比绍',
        'GNQ' => '赤道几内亚',
        'GRC' => '希腊',
        'GRD' => '格林纳达',
        'GRL' => '格陵兰',
        'GTM' => '危地马拉',
        'GUM' => '关岛',
        'GUY' => '圭亚那',
        'HKG' => '中国香港',
        'HND' => '洪都拉斯',
        'HRV' => '克罗地亚',
        'HTI' => '海地',
        'HUN' => '匈牙利',
        'IDN' => '印度尼西亚',
        'IMN' => '马恩岛',
        'IND' => '印度',
        'IRL' => '爱尔兰',
        'IRN' => '伊朗',
        'IRQ' => '伊拉克',
        'ISL' => '冰岛',
        'ISR' => '以色列',
        'ITA' => '意大利',
        'JAM' => '牙买加',
        'JEY' => '泽西岛',
        'JOR' => '约旦',
        'JPN' => '日本',
        'KAZ' => '哈萨克斯坦',
        'KEN' => '肯尼亚',
        'KGZ' => '吉尔吉斯斯坦',
        'KHM' => '柬埔寨',
        'KNA' => '圣基茨和尼维斯',
        'KOR' => '韩国',
        'KWT' => '科威特',
        'LAO' => '老挝',
        'LBN' => '黎巴嫩',
        'LBR' => '利比里亚',
        'LBY' => '利比亚',
        'LCA' => '圣卢西亚',
        'LIE' => '列支敦士登',
        'LKA' => '斯里兰卡',
        'LTU' => '立陶宛',
        'LUX' => '卢森堡',
        'LVA' => '拉脱维亚',
        'MAC' => '中国澳门',
        'MAF' => '法属圣马丁',
        'MAR' => '摩洛哥',
        'MCO' => '摩纳哥',
        'MDA' => '摩尔多瓦',
        'MDG' => '马达加斯加',
        'MDV' => '马尔代夫',
        'MEX' => '墨西哥',
        'MKD' => '北马其顿',
        'MLI' => '马里',
        'MLT' => '马耳他',
        'MMR' => '缅甸',
        'MNE' => '黑山',
        'MNG' => '蒙古',
        'MOZ' => '莫桑比克',
        'MUS' => '毛里求斯',
        'MWI' => '马拉维',
        'MYS' => '马来西亚',
        'NAM' => '纳米比亚',
        'NGA' => '尼日利亚',
        'NIC' => '尼加拉瓜',
        'NLD' => '荷兰',
        'NOR' => '挪威',
        'NPL' => '尼泊尔',
        'NRU' => '瑙鲁',
        'NZL' => '新西兰',
        'OMN' => '阿曼',
        'PAK' => '巴基斯坦',
        'PAN' => '巴拿马',
        'PER' => '秘鲁',
        'PHL' => '菲律宾',
        'PLW' => '帕劳',
        'PNG' => '巴布亚新几内亚',
        'POL' => '波兰',
        'PRI' => '波多黎各',
        'PRT' => '葡萄牙',
        'PRY' => '巴拉圭',
        'PSE' => '巴勒斯坦',
        'PYF' => '法属波利尼西亚',
        'QAT' => '卡塔尔',
        'REU' => '留尼汪',
        'ROU' => '罗马尼亚',
        'RUS' => '俄罗斯',
        'RWA' => '卢旺达',
        'SAU' => '沙特阿拉伯',
        'SDN' => '苏丹',
        'SEN' => '塞内加尔',
        'SGP' => '新加坡',
        'SLE' => '塞拉利昂',
        'SLV' => '萨尔瓦多',
        'SOM' => '索马里',
        'SRB' => '塞尔维亚',
        'SUR' => '苏里南',
        'SVK' => '斯洛伐克',
        'SVN' => '斯洛文尼亚',
        'SWE' => '瑞典',
        'SWZ' => '斯威士兰',
        'SXM' => '荷属圣马丁',
        'SYC' => '塞舌尔',
        'SYR' => '叙利亚',
        'TGO' => '多哥',
        'THA' => '泰国',
        'TKM' => '土库曼斯坦',
        'TON' => '汤加',
        'TTO' => '特立尼达和多巴哥',
        'TUN' => '突尼斯',
        'TUR' => '土耳其',
        'TWN' => '中国台湾',
        'TZA' => '坦桑尼亚',
        'UGA' => '乌干达',
        'UKR' => '乌克兰',
        'URY' => '乌拉圭',
        'USA' => '美国',
        'UZB' => '乌兹别克斯坦',
        'VEN' => '委内瑞拉',
        'VGB' => '英属维尔京群岛',
        'VIR' => '美属维尔京群岛',
        'VNM' => '越南',
        'VUT' => '瓦努阿图',
        'XKK' => '科索沃',
        'YEM' => '也门',
        'ZAF' => '南非',
        'ZMB' => '赞比亚',
        'ZWE' => '津巴布韦',
        'ZZZ' => '未知地区',
    ];

    public static function format(string $code): string
    {
        $normalized = self::normalize($code);

        if ($normalized === '') {
            return '';
        }

        return isset(self::NAMES[$normalized]) ? $normalized.' - '.self::NAMES[$normalized] : $normalized;
    }

    public static function name(string $code): ?string
    {
        $normalized = self::normalize($code);

        return self::NAMES[$normalized] ?? null;
    }

    private static function normalize(string $code): string
    {
        return strtoupper(trim($code));
    }
}
